COR1 = 'red'
COR2 = 'yellow'
JOGADOR1 = 1
JOGADOR2 = 2
BLOCO_A = 1
BLOCO_B = 2
BLOCO_S = 'imagens/blocos/blocoS.gif'
BLOCO_C = 'imagens/blocos/blocoC.gif'
ORIENTACAO = true
ANIMACAO= false
SERVIDOR = "damstvserver.agilityhoster.com"
--SERVIDOR = "www.midiacom.uff.br/~caleb/damstvserver"
IDS = {'caleb','ad'}
